### ISSUE TITLE
spawn ENOENT & 应该使用哪个版本的node？

### ISSUE THREAD

**Issue by RangerNJU** [stkevintan/canoe-blog#16]
你好~很喜欢这个主题，不过没有学过前端的知识。

目前尝试用node 8+gulp3.9.1运行：

这是nvm list的输出：
```bash
nvm list
        v6.17.1
->      v8.17.0
       v10.22.1
       v12.19.0
         system
default -> 12 (-> v12.19.0)
node -> stable (-> v12.19.0) (default)
stable -> 12.19 (-> v12.19.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> v12.19.0)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1
lts/carbon -> v8.17.0
lts/dubnium -> v10.22.1
lts/erbium -> v12.19.0
```
尝试运行`gulp build`时报错：
```bash
...
Starting 'copy:static'...

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/ranger/37Percent/node_modules/optipng-bin/vendor/optipng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

如果只运行`hugo serve`的话，看到的主页html所有元素都堆在左边，推测应该是因为static里的相关文件都没有拷贝到指定位置？

其他信息：
用的是Arch Linux：
```bash
                   -`                    ranger@Mi3 
                  .o+`                   ---------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: WRT-WX9 M1260 
               `+oooooo:                 Kernel: 5.3.13-arch1-1 
               -+oooooo+:                Uptime: 14 hours, 17 mins 
             `/:-:++oooo+:               Packages: 952 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 2160x1440 
          `/+++ooooooooooooo/`           WM: i3 
         ./ooosssso++osssssso+`          Theme: Adapta-Nokto [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Papirus-Dark [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: xfce4-terminal 
      :osssssss/        osssso+++.       Terminal Font: DejaVu Sans Mono for Powerline 27 
     /ossssssss/        +ssssooo/-       CPU: Intel i3-8145U (4) @ 3.900GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel UHD Graphics 620 
  `+sso+:-`                 `.-/+oso:    Memory: 5047MiB / 7709MiB 
 `++:.                           `-/+/
 .`                                 `/                           
```

**Comment by stkevintan** [comment]
试试在root目录新建一个.tmp文件夹

**Comment by RangerNJU** [comment]
重新`git clone`一遍整个项目。
然后指定使用node 8并重新构建sass：
```bash
nvm use 8 && npm rebuild node-sass && npm install
```

确认创建了`/root/.tmp`:
```bash
sudo ls -al /root/ | grep ".tmp"
drwxr-xr-x  2 root root  4096 Oct 12 12:57 .tmp
```
运行`gulp build`:
```bash
[12:58:48] Using gulpfile ~/canoe-blog/gulpfile.js
[12:58:48] Starting 'clean'...
[12:58:48] Finished 'clean' after 53 ms
[12:58:48] Starting 'build'...
[12:58:48] Starting 'build:dev'...
[12:58:48] Starting 'hugo'...
[12:58:49] Start building sites … 

[12:58:49] 

[12:58:49]                    | EN   
-------------------+------
  Pages            | 222  
  Paginator pages  |   9  
  Non-page files   |   0  
  Static files     |   0  
  Processed images |   0  
  Aliases          |  77  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 451 ms

[12:58:49] hugo process exited with code 0
[12:58:49] Finished 'hugo' after 487 ms
[12:58:49] Starting 'style'...
[12:58:49] Starting 'script'...
[12:58:49] Starting 'image'...
[12:58:49] Starting 'pimg'...
[12:58:49] Starting 'copy:static'...
[12:58:49] Starting 'lunr'...
[12:58:50] Finished 'lunr' after 906 ms

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/ranger/canoe-blog/node_modules/optipng-bin/vendor/optipng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

此时运行`git status`会显示`package-lock.json`有改动，节选一部分如下：
```bash
       "integrity": "sha1-z6I7xYQPkQTOMqZedNt+epdLvuE=",
       "dev": true,
       "requires": {
-        "acorn": "5.3.0",
-        "css": "2.2.1",
-        "normalize-path": "2.1.1",
-        "source-map": "0.5.7",
-        "through2": "2.0.3"
+        "acorn": "^5.0.3",
+        "css": "^2.2.1",
+        "normalize-path": "^2.1.1",
+        "source-map": "^0.5.6",
+        "through2": "^2.0.3"
       },
```
主要是版本号有一些变动，查了一下应该是是`npm install`会更新版本号。
在[这个问答中](https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json)提到`To be clear: package-lock.json alone no longer locks the root level dependencies!`，不知道是不是应该用npm 5.0.0？
当前我系统中的npm版本是：
```bash
npm --version
6.13.4
```

**Comment by stkevintan** [comment]
看了一下，应该是imagemin的问题。
尝试在gulpfile.js里删除或者注释掉下面几行：
```diff
// => dev
gulp.task("image", () => {
  const destDir = env === "theme" ? `${themeDir}/static/img` : `${devDir}/img`;
  return gulp
    .src(`${srcDir}/image/**/*.{png,jpg}`)
    .pipe(changed(destDir))
-    .pipe(
-      $if(
-        env !== "dev",
-        imagemin({
-          progressive: true,
-          use: [pngquant({ quality: 90 })]
-        })
-      )
-    )
    .pipe(gulp.dest(destDir))
    .pipe(bs.stream({ match: "**/*.{png,jpg}" }));
});

gulp.task("pimg", () => {
  const destDir = `${devDir}/pimg`;
  return gulp
    .src(`pimg/**/*.{png,jpg}`)
    .pipe(changed(destDir))
-    .pipe(
-      $if(
-        env !== "dev",
-        imagemin({
-          progressive: true,
-          use: [pngquant({ quality: 90 })]
-        })
-      )
-    )
    .pipe(gulp.dest(destDir))
    .pipe(bs.stream({ match: "**/*.{png,jpg}" }));
});
```

**Comment by RangerNJU** [comment]
能够成功执行`gulp serve`在本地浏览器看到Blog啦，动态效果很棒！
BTW可以提供一波微信/支付宝付款码哦（好看到想给钱哈哈哈，请您喝杯奶茶）

有几个小问题：
1. 页首状态栏中的图标我选用了[这个网站](https://www.materialui.co/icon/search)提供的SVG图并在svg标签中添加fill=#fff得到白色图标，但是显示上似乎search/apps/rss_feed几个图标的上下边界肉眼可见不在同一水平线上？希望得到平整的图标是不是需要自己调整SVG参数呢？或者通过某种方式能够让网页调用[font awesome cheatsheet](https://fontawesome.com/cheatsheet)里的图标？
![screenshot_20201012_215512](https://user-images.githubusercontent.com/71978856/95755616-9c08e100-0cdf-11eb-9f0b-45cd5e72546d.png)
2. 一言的服务似乎没有正常工作？还是说只在本地预览的话不会连接服务器?
![screenshot_20201012_215520](https://user-images.githubusercontent.com/71978856/95755895-f0ac5c00-0cdf-11eb-857e-6dfe3927e108.png)
3. 有两处图片应该是本地素材缺失或者路径错误（也有可能是我的系统上没有安装对应的字体文件）显示为方框中一个X，请问这两处图标对应的代码在什么地方？
![screenshot_20201012_220440](https://user-images.githubusercontent.com/71978856/95756533-df178400-0ce0-11eb-9bec-d7ff1ef22c35.png)
![screenshot_20201012_220447](https://user-images.githubusercontent.com/71978856/95756549-e2127480-0ce0-11eb-8396-e52b4c1b9fa4.png)
4. 在contents文件夹的Posts中写md文档就能在博客中展现新博文吗？可是首页中只有Posts一个卡片，点击卡片才能看到所有的博文。如果我希望直接在首页中展现所有的博文，应该改动哪些位置的配置文件？（如果直接把Posts中的*.md移到contents文件夹下，posts卡片也消失了；如果删除Posts文件夹则构建静态站点失败）
![screenshot_20201012_215526](https://user-images.githubusercontent.com/71978856/95757829-9b257e80-0ce2-11eb-9078-227a74f1d41c.png)
5. 评论系统下的`Code 504`如何去除？
![screenshot_20201012_223311](https://user-images.githubusercontent.com/71978856/95758468-7f6ea800-0ce3-11eb-9785-0cc337066709.png)
6. 有标题的文章中，右侧TOC会因为中文字体的加入而使得高亮选区偏移。请问这一部分的字体设置（字体族和字体大小）在哪一段配置文件中？
![screenshot_20201012_223521](https://user-images.githubusercontent.com/71978856/95758730-cb215180-0ce3-11eb-8842-3490ea292760.png)
7. 运行`gulp serve`console内有提示，不知道是不是要修改一下node中软件的版本？
```bash
node_modules/whatwg-fetch/fetch.js (461:40) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
```

**Comment by stkevintan** [comment]
sorry, 这个项目已经好几年没维护了，肯定很多东西变化了。我也没有时间和精力再来维护。你可以自己捣鼓一下， good luck
