### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by Livingston34** [stkevintan/canoe-blog#5]
I can not run this project , has run error message  

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn hugo ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Enter-tainer** [comment]
Try to change your node version. This might help

**Comment by stkevintan** [comment]
you should install `hugo` at first

**Comment by Livingston34** [comment]
Thanks , the project is running

**Comment by Livingston34** [comment]
Did you have version one code? I like version two than version one !

**Comment by stkevintan** [comment]
here: https://github.com/stkevintan/hugo-YAMT-theme/tree/v1
